USE [master]
GO

CREATE DATABASE [demo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'project', FILENAME = N'/var/opt/mssql/data/project.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'project_log', FILENAME = N'/var/opt/mssql/data/project_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [demo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [demo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [demo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [demo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [demo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [demo] SET ARITHABORT OFF 
GO

ALTER DATABASE [demo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [demo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [demo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [demo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [demo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [demo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [demo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [demo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [demo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [demo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [demo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [demo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [demo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [demo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [demo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [demo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [demo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [demo] SET RECOVERY FULL 
GO

ALTER DATABASE [demo] SET  MULTI_USER 
GO

ALTER DATABASE [demo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [demo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [demo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [demo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [demo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [demo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [demo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [demo] SET  READ_WRITE 
GO


USE [demo];
CREATE TABLE [dbo].[Projects](
	[ProjectID] [int] IDENTITY(1,1) NOT NULL,
	[ProjectName] [varchar](50) NULL,
	[FileName] [varchar](50) NULL,
	[CreatedOn] [datetime] NULL,
	[LastUpdated] [datetime] NULL,
	[ProjectStatus] int NULL,
	[ProjectType] int NULL,
	[CreatedBy] [varchar](50) NULL,
 CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED 
(
	[ProjectID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


